.storybook/main.js
.storybook/preview.js
package.json
yarn.lock

> closed #5 
- `storybook-mobile` package 다운로드
- 스토리북 addons 패키지 플러그인 추가
- 스토리북 모바일 환경 테스트를 위한 체킹
- 필요하다고 생각하는 360, 375, 414px 사이즈 커스텀 사이즈 생성

[feat #5] Storybook Mobile 세팅 

---

.storybook/main.js
.storybook/preview.js
package.json
src/stories/components/Text.stories.jsx
yarn.lock

> closed #4 
- Storybook TestCode 작성
- Storybook Netlify 배포 CI/CD 세팅 완료
- 스토리북 자동 배포 완료 => Main 브랜치에 적용 예정
- https://jungdam-storybook.netlify.app/

[feat #4] StoryBook 디렉토리 세팅 및 Deploy 

---

src/components/base/Image/index.jsx
src/stories/components/Image.stories.jsx

> closed #20
- `objectFit` mode Default 중복 설정 해결
- display `&&` 연산자 적용
- 이미지 코드 리팩토링 작업

[refactor #20]

---

src/components/base/Spinner/index.jsx
src/components/base/index.jsx
src/stories/components/Spinner.stories.jsx

> closed #21 
- Loading 을 위한 Spinner 컴포넌트 구현
- 사용자는 `size`를 통해 스피너 사이즈를 정할 수 있다.
- `24`, `16` 숫자로만 입력해도 적용 된다. 
- 사용자는 `isLoading` props로 `boolean` 값을 지정해 반환 여부를 결정한다.
- default `true`이며 false를 통해 `null` 을 반환한다. 
- 사용자는 `color`를 통해 Spinner의 stroke 색깔을 변경 할 수 있다.
- Link : https://deploy-preview-33--jungdam-storybook.netlify.app/?path=/story/components-spinner--default

[feat #21]

---

src/assets/colors/Color.jsx
src/assets/fonts/Font.jsx
src/components/base/Button/index.jsx
src/components/base/index.jsx
src/stories/components/Button.stories.jsx

> closed #18
- Button 컴포넌트 제작
- `mode` 를 통한 버튼 타입 지정 
- 미 입력 : Button 시멘틱 태그 역할 
- `Primary` : 꽉찬 기본 버튼
- `Border` : 외곽선이 존재하는 버튼 
- `bgColor` 를 통한 백그라운드 컬러 설정 (Primary 적용)
- `gap`을 통한 버튼 안의 요소 사이의 간격 설정
- Button 스토리 북 세팅
- Button 컴포넌트 구현 완료
- 아이콘/텍스트/아이콘+텍스트 3가지 버전으로 Storybook 제공
- OnClick 이벤트 적용 여부 확인 가능 
- Link : https://deploy-preview-34--jungdam-storybook.netlify.app/?path=/story/components-button--default

[feat #18]

---

src/components/base/Skeleton/Base.jsx
src/components/base/Skeleton/Box.jsx
src/components/base/Skeleton/Circle.jsx
src/components/base/Skeleton/Line.jsx
src/components/base/Skeleton/index.jsx
src/components/base/index.jsx
src/stories/components/Skeleton.stories.jsx

> closed #28
- Skeleton UI 구현 완료
- Box, Circle, Line 3가지 모양의 UI 제공 
- 사용법은 주석 명시 및 스토리북 참조
- Skeleton UI 컴포넌트 구현 완료
- https://deploy-preview-37--jungdam-storybook.netlify.app/?path=/story/components-skeleton--box

[feat #28]

---

src/components/base/Avatar/index.jsx
src/components/base/index.jsx
src/stories/components/Avatar.stories.jsx

> closed #19 
- Avatar Component 생성
- Avatar Storybook 생성
- prop 을 통해 size 를 `base`, `large` 로 사용 가능하다.
- `defaultProps` 를 통해 default image 로 기본 아바타 샘플 src 가 들어간다.
https://deploy-preview-31--jungdam-storybook.netlify.app/?path=/story/component-avatar--default
- base
- large

[feat #19]

---

src/components/base/Modal/index.jsx
src/components/base/index.jsx
src/hooks/index.jsx
src/hooks/useClickAway.jsx
src/stories/components/Modal.stories.jsx

> closed #32 
- Modal Component 생성
- useClickAway hook 생성
- Modal Storybook 생성
- 기본적인 모달 버튼은 현재 모두 close 기능만을 가지고 있습니다.
- 예, 아니오 버튼은 나중에 버튼 컴포넌트가 만들어지면 변경하겠습니다.
- width 의 default 를 60% 로 가져가서 폭에 맞게 변경되도록 했습니다.
https://deploy-preview-35--jungdam-storybook.netlify.app

[feat #32]

---

src/components/base/Input/index.jsx
src/components/base/index.jsx
src/stories/components/Input.stories.jsx

> closed #36 
- Input Component 생성
- Input Storybook 생성
- onChange 이벤트만 연결해두었습니다.
- 날짜를 정하는 Input 은 기본 `type='date'` 를 사용하였습니다.
-  성공, 실패, 비활성 시에는 밑줄로 구분하게 했습니다.
https://deploy-preview-41--jungdam-storybook.netlify.app
- Default
- Date
- Small
- Error
- Success
- Disabled

[feat #36]

---

src/components/base/Avatar/index.jsx
src/stories/components/Avatar.stories.jsx

> closed #45 
- Storybook Component -> Components 변경
- Default Image 변경
- Storybook 경로 변경과 이미지 변경을 하였습니다.
- 혹시 이미지가 별로시면 말씀해주세요!
https://deploy-preview-57--jungdam-storybook.netlify.app

[feat #45] 

---

src/components/base/Button/index.jsx
src/styles/ResetStyle.jsx

> closed #62
- 원인 : 아이폰 모바일 ButtonComponent 색깔 미적용 문제 발생
- 해결 : 버튼 Color 값 초기화
- 추가 설정 : Link 관련 Default값 초기화 
- 버튼 관련 버그 fixed

[feat #62]

---

src/stories/components/Divider.stories.jsx
src/stories/components/Image.stories.jsx
src/stories/components/Spinner.stories.jsx

> closed #66
- storybook craco 업데이트 이후 Fragment 미적용 오류 발생
- div 태그로 변경하여 해결
- 스토리북 오류 해결 완료

[feat #66]

---

src/components/base/Textarea/index.jsx
src/components/base/index.jsx
src/stories/components/Textarea.stories.jsx

> closed #53 
- Textarea 컴포넌트 / 스토리북 생성
- 일기 느낌에 맞게 밑줄이 그어진 형태로 생성하였습니다.
- 기본 3줄만 보여지며, 3줄이 넘어가게되면 해당 textarea 내부에서 스크롤되어 내려가는 형식입니다.
https://deploy-preview-58--jungdam-storybook.netlify.app
- 3줄 이상 넘어갈 경우 아래처럼 textarea 내에서 스크롤되어 내려갑니다

[feat #53]

---

src/components/base/ProgressBar/index.jsx
src/components/base/index.jsx
src/stories/components/ProgressBar.stories.jsx

> closed #26 
- ProgressBar 컴포넌트 구현
- ProgressBar 스토리북 구현
- 상태 값 반영에 따른 유동적인 ProgressBar 컴포넌트를 구현하였습니다.
- args
- totalStep : 총 몇 단계의 작업을 진행하는 ProgressBar를 생성할 지에 대한 입력 값 입니다.
- currentStep: 전체 단계 중 현재는 몇 번째 단계에 위치하는지에 대한 입력 값 입니다.
- https://deploy-preview-76--jungdam-storybook.netlify.app

[feat #26] ProgressBar 컴포넌트 구현

---

src/components/domain/UserCard/index.jsx
src/components/domain/index.jsx

> closed #75 
- 멤버리스트 페이지에 사용될 멤버 UserCard 도메인 추가
- 멤버리스트에서 사용될 UserCard 도메인을 추가하였습니다.

[feat #75]

---

src/common/utils/constants.jsx
src/pages/LoginPage/index.jsx
src/router/Router.jsx

> closed #100
- 라우터 재정립, 사용 시 주석 풀고 사용하면 됩니다.
```js
// Depth를 2-3단계로 최대한 보기 편하게 노력했지만.. 최선인 듯 합니다
<Route element={<AuthRoute />}>
<Route path="/album" element={<AlbumListPage />}>
<Route path="new" element={<AlbumCreatePage />} />
<Route path="profile" element={<ProfilePage />} />
</Route>
<Route path="/album/:albumId" element={<AlbumMainPage />}>
<Route path="diary">
<Route path=":diaryId" element={<DiaryCreatePage />} />
<Route path="new" element={<DiaryCreatePage />} />
</Route>
<Route path="members" element={<MemberListPage />}>
<Route path="invite" element={<MemberInvitePage />} />
</Route>
<Route path="settings" element={<AlbumSettingPage />}>
<Route path="edit" element={<AlbumSettingEditPage />} />
</Route>
<Route path="storybook" element={<StorybookPage />} />
<Route path="moment" …
```

[refactor #100]

---

src/pages/AlbumSettingsPage/index.jsx

> closed #104 
- ALBUM_SETTINGS_LIST 앨범 제거 삭제 & 경로 지정
- Divider 컴포넌트 사용
- ALBUM_SETTINGS_LIST 에서 앨범 제거를 삭제하고, 경로를 명시해주어 이동이 가능하게 설정했습니다.
- DIvider 컴포넌트를 사용하여 리펙토링하였습니다.
- 기타 단어 수정 등 작은 수정사항이 있었습니다.

[feat #104]

---

src/pages/AlbumSettingsEditPage/index.jsx
src/pages/AlbumSettingsPage/index.jsx

> closed #111 
- styled component font 에러 해결
- 에러메세지 출력 안되는 것 확인 완료!

[feat #111]

---

src/pages/TestPage/index.jsx
src/router/Router.jsx

> closed #114
- `/test/닉네임` `router` 입력 시, token 저장 후 
- `/test/choi`
- choi
- hoon
- bingle
```js
{/* TestRoute - 각 Choi/Hoon/Bingle*/}
<Route path="/test/:name" element={<TestPage />} />
```
```js
if (name) {
dispatch(setToken(DUMMY_LIST[name]));
dispatch(fetchMemberLogin());
navigate('/');
} else {
alert('닉네임이 잘못 입력되었어요.');
navigate('/login');
}
```

[feat #114]

---

src/assets/colors/index.jsx
src/components/base/Image/index.jsx
src/components/domain/StoryBookDiaryList/index.jsx
src/components/domain/index.jsx
src/pages/StoryBookPage/index.jsx
src/pages/index.jsx
src/router/Router.jsx

> closed #107 
- StorybookPage 구현 완료
- DUMMY_DATA 적용 
- 더보기 버튼 추가
- `Link` 처리 완료 
- DimImage 컬러 및 사용 props 추가 
- `dimHeight` 를 통해 dimBox의 높이 설정 가능 
- 스토리북의 메인이 되는 페이지를 구현.

[feat #107]

---

package.json
src/common/api/api.jsx

> closed #123
- API 모듈 BASE_URL 환경 변수 처리 완료
- Proxy API URL 제거하기

[feat #123] 

---

src/pages/MemberListPage/index.jsx
src/router/Router.jsx

> closed #116 
- UserCard 와 Divider 컴포넌트 사용
- DUMMYDATA 테스트
- UserCard 컴포넌트를 연결시켜서 리스트 구현 (API x)

[feat #116]

---

src/pages/SpecialMomentPage/index.jsx
src/pages/index.jsx
src/router/Router.jsx

> closed #122 
- Swiper 라이브러리를 사용하여 특별한 순간 페이지 구현
- DUMMYDATA 연결
- ClickEvent 는 아직 연결되지 않았습니다.
- `coverflowEffect={{ }}` 내부의 주석처리된 코드는 없어도 큰 지장은 없는 코드인 것으로 판단해서 일단 주석처리해두었습니다. 이후에 동작을 정확히 파악하고 추가 / 제거 하겠습니다.
- pagination 은 사용하지 않는 걸로 구현해보았는데 의견이 궁금합니다!
- 넘어온 데이터가 없을 때 렌더링을 추가해야합니다. (깜빡했어요)
- 문제사항
- 모바일서버 테스트(아이폰) 했을 때, 스와이프할 때 너무 뚝뚝 끊기는 느낌이 심한 것 같습니다.. 
---
---
- pagenation 있는 디자인

[feat #122]

---

src/common/api/api.jsx
src/common/api/postDiaryCreate.jsx
src/common/api/postImageUpload.jsx
src/common/utils/getBase64ToFile.jsx
src/common/utils/getUploadImageUrls.jsx
src/components/base/Textarea/index.jsx
src/components/base/Upload/index.jsx
src/components/domain/DiaryCreateStepOne/index.jsx
src/components/domain/DiaryCreateStepThree/index.jsx
src/components/domain/DiaryCreateStepTwo/index.jsx
src/hooks/index.jsx
src/hooks/useForm.jsx
src/hooks/usePromise.jsx
src/pages/DiaryCreatePage/index.jsx

> closed #110 
- 사용자 입력 값을 중앙 제어식으로 상태 관리 구현
- 위의 구현을 통해 사용자가의 단계별 UI 이동에서도 상태가 유지된 상태로 수정이 가능하다.
- 사용자 입력 폼 예외 처리 구현
- 이미지 업로드 API 구현
- 일기 생성 API 구현
- usePromise 커스텀 훅 구현
- useForm 커스텀 훅 파일리스트 데이터 반영 가능하도록 기능 확장
- 일기 생성 페이지의 API 통신을 구현하면서 상태 관리 코드 리팩토링이 많이 진행되었다.
- 일기 생성 기능을 구현하였다.

[feat #110] 일기 생성 페이지 API 통신 구현

---

src/common/api/albumApi.jsx
src/components/domain/AlbumSwiper/index.jsx
src/hooks/index.jsx
src/hooks/useAlbumValidation.jsx
src/pages/AlbumListPage/index.jsx
src/router/AlbumValidationRoute.jsx
src/router/Router.jsx
src/router/index.jsx

> closed #145 
- 앨범 페이지를 url로 그냥 접속하는 부분에 있어서 앨범 소속으로 존재하는 지 유효성 검사 체킹
- `AlbumValidationRoute` : 앨범 유효성 검사가 이루어지는 Route 설정 완료
- `useAlbumValidation` : 앨범 유효성 검사를 위한 hook
- 앨범 유효성 검사 기능 구현 완료

[feat #145]

---

src/common/api/inviteUser.jsx
src/common/api/memberList.jsx
src/common/api/searchUser.jsx
src/components/base/Modal/index.jsx
src/pages/MemberInvitePage/index.jsx

> closed #148 
- API 연동한 기능 동작 확인
- 그림자 수정
- API 분리
- 리뷰사항을 적용하였습니다.
- 초대 리스트에 추가된 유저를 삭제하는 기능은 고도화 작업에서 이루어져야 할 것 같습니다. 🥲

[feat #148]

---

src/common/api/getMemberList.jsx
src/components/domain/UserCard/index.jsx
src/pages/MemberListPage/index.jsx

> closed #150 
- 앨범 멤버 리스트 API 연동
- 앨범 멤버 리스트를 API 연동하였습니다.
- 로딩중일 때 스켈레톤을 렌더링했는데 어색하진 않을지..
- 모바일로 접속이 안되고있어서 아직 모바일 테스트는 하지 못한 상황입니다. 이슈있으면 작성하겠습니다!
- 스켈레톤 출력 상태 (로딩중)

[feat #150]

---

src/components/domain/AlbumMainHeader/index.jsx
src/components/domain/Navigation/index.jsx
src/pages/DiaryCreatePage/index.jsx
src/pages/DiaryPage/index.jsx

> closed #160 
- Navigation 라우팅 경로 지정
- 일기 상세 페이지 뒤로가기 기능 구현
- 일기 생성 페이지 뒤로가기 기능 구현
- 라우팅과 관련된 버튼들의 경로 지정을 통한 라우팅 기능 구현

[feat #160] 네비게이션, 뒤로가기, 설정 버튼 라우팅 경로 지정

---

src/components/domain/StoryBookDiaryList/index.jsx
src/pages/StoryBookDetailPage/index.jsx
src/pages/StoryBookPage/index.jsx

> closed #170
- 각종 키값 버그사항 및 스토리북 메인 Default처리 완료
- 버그 수정

[feat #170]

---

src/components/domain/AlbumMainTimeline/index.jsx

> closed #163 
- 이미지 슬라이더 데이터 조회 형식 변경
- 이미지 슬라이더 데이터 조회 형식 변경

[feat #163] 이미지 슬라이더 데이터 조회 형식 변경

---

src/components/domain/AlbumMainTimeline/index.jsx

> closed #177 
-  컴포넌트 스타일 수정
앨범 메인 페이지 일기 리스트 스타일 수정

[Feat #177] 앨범 메인 페이지 일기 리스트 스타일 수정

---

src/pages/OAuthRedirect/index.jsx
src/redux/store.jsx

- redux testing plugin on
- OAuthRedirect 설정

1.0.0.ver refactor : redux, OAuthRedirect 재설정

---

src/redux/store.jsx

> closed #이슈넘버
- task1
- task2
- task3

🐛 fix : 경고 메세지 제거

---

src/common/api/deleteDiary.jsx
src/components/domain/DiaryHeaderInfo/index.jsx
src/pages/DiaryPage/index.jsx

> closed #189 
- 일기 삭제 api 구현
- 일기 삭제 기능 구현
- 삭제 시 사용자 최종 확인을 위한 모달 구현
- 일기 상세 페이지의 일기 삭제 기능을 구현

[feat #189] 일기 상세 페이지 일기 삭제 구현

---

src/pages/MemberListPage/index.jsx

> closed #192 
- 멤버리스트페이지 네비게이션 추가

[feat #192]

---

src/pages/AlbumSettingsEditPage/index.jsx
src/pages/AlbumSettingsPage/index.jsx
src/pages/MemberInvitePage/index.jsx
src/pages/SpecialMomentPage/index.jsx

> closed #195 
- 멤버리스트 / 앨범설정 부분 뒤로가기 수정 & 제출 후 이전페이지로 이동 추가
- 멤버 초대 시 초대 완료 메세지 alert 출력
- 특별한 순간 Default 텍스트 출력

[feat #195]

---

src/pages/AlbumSettingsEditPage/index.jsx

> closed #197
- 앨범 정보 수정 입력값이 없을 경우 alert 출력

[feat #197]

---

src/pages/AlbumCreatePage/index.jsx

> closed #202 
- Album CreatePage에서 뒤로 가기 시 에러 발생 메세지 해결

[feat #202]

---

src/styles/ResetStyle.jsx

> closed #204
- reset CSS에 IOS Input에 대응하기 위해 전역 초기화 값 추가

[feat #204]

---

src/common/utils/getTodayDate.jsx
src/components/domain/DiaryCreateStepOne/index.jsx
src/pages/DiaryCreatePage/index.jsx

> closed #201 
- getTodayDate 함수 모듈화
- 일기 생성 미래 날짜 입력 값에 대한 예외 처리 추가
- 일기 생성 날짜 입력 값 예외 처리 구현

[feat #201] 일기 생성 날짜 입력 값 예외 처리 구현

---

src/common/api/memberApi.jsx
src/components/domain/AlbumInviteList/AlbumInviteCard.jsx
src/components/domain/ProfileList/index.jsx
src/redux/member/index.jsx
src/router/AlbumValidationRoute.jsx

> closed #208 
- 앨범 초대 수락 시, 해당 앨범 Redirect
- 로그아웃 기능 추가
- 멤버 역할 가져오는 API 설정

[feat #208]

---

src/common/api/searchUser.jsx
src/components/domain/Header/index.jsx
src/pages/MemberInvitePage/index.jsx

> closed #221
- 헤더 밀림 수정 테스트
- 멤버 초대 API 수정

[feat #221]

---

src/components/domain/DiaryCreateStepOne/index.jsx
src/components/domain/DiaryCreateStepTwo/index.jsx
src/pages/DiaryCreatePage/index.jsx

> closed #214 
- 일기 생성 페이지 가상 키보드 활성화에 따른 버튼 UI 수정
- 화면의 동적인 사이즈에 따른 버튼 UI 적용

[feat #214] 일기 생성 페이지 가상 키보드 활성화에 따른 버튼 UI 수정

---

src/pages/ResponseDefaultPage/index.jsx
src/pages/index.jsx
src/styles/DefaultTemplate.jsx

> closed #217
- 데스크탑 및 태블릿 환경에서 Default 페이지 출력
- Resizing 사이즈 제공으로 사이즈 안내

[feat #217]

---

README.md
public/index.html
src/components/base/Avatar/index.jsx
src/components/domain/AlbumInviteList/AlbumInviteCard.jsx
src/components/domain/AlbumMainHeader/index.jsx
src/components/domain/AlbumMainTimeline/index.jsx
src/components/domain/DiaryComment/index.jsx
src/components/domain/DiaryCommentInputForm/index.jsx
src/components/domain/DiaryCreateStepOne/index.jsx
src/components/domain/DiaryCreateStepThree/index.jsx
src/components/domain/DiaryCreateStepTwo/index.jsx
src/components/domain/DiaryImages/index.jsx
src/components/domain/Header/index.jsx
src/pages/AlbumCreatePage/AlbumCreateStep2.jsx
src/pages/AlbumListPage/index.jsx
src/pages/AlbumMainPage/index.jsx
src/pages/AlbumSettingsEditPage/index.jsx
src/pages/AlbumSettingsPage/index.jsx
src/pages/DiaryCreatePage/index.jsx
src/pages/MemberInvitePage/index.jsx
src/pages/MemberListPage/index.jsx
src/pages/SpecialMomentPage/index.jsx
src/pages/StoryBookPage/index.jsx
src/styles/ResetStyle.jsx

> closed #이슈넘버
- task1
- task2
- task3

v1.0.2 버그Hotfix

---

src/components/domain/AlbumMainHeader/index.jsx
src/components/domain/Header/index.jsx
src/pages/AlbumSettingsEditPage/index.jsx
src/pages/AlbumSettingsPage/index.jsx
src/pages/MemberInvitePage/index.jsx
src/pages/SpecialMomentPage/index.jsx

> closed #216 
- 헤더 rightcomponent 위치 수정 완료
- 헤더 Admin 여부 props 로 그룹 설정 페이지 아이콘 수정 
- 특별한 순간 아무 게시글도 없을 때 UI 수정 (텍스트 nowrap)
- 앨범정보수정 버튼 크기 padding 으로 fix
- 해야할 것 (진행중)

[feat #216]
